version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    groups:
      keycloak:
        patterns:
          - "org.keycloak:*"
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
